### ISSUE TITLE
Travis CI tests break when using latest TBB

### ISSUE THREAD

**Issue by mjuarezm** [webfp/tor-browser-selenium#1]
When using **TBB 5.5.3** for the tests, Selenium cannot connect to the TorBrowser (Firefox) driver. The message error from Firefox logs points to a problem with **glibc**:

> tor-browser_en-US/Browser/firefox: relocation error: ../tor-browser_en-US/Browser/firefox: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

 I am able to reproduce it running the tests on an Ubuntu 14.04. The problem goes away when using newer versions of Ubuntu, as they have a newer version of glibc that allows running the firefox binary in TBB. However, Travis only supports instances of Ubuntu up to 14.04.

I am using TBB 4.5.1 for now. Any suggestion on how to solve this problem?

**Comment by gunesacar** [comment]
This should be fixed by https://github.com/webfp/tor-browser-selenium/commit/44d45155aca67ce48d82beef5db795e1c627344b#diff-90b997cd7ab4ac2662e5c93754be153bR73.

I had the problem with all the TBB versions. I think this was due to missing call to export_lib_path() which sets up the environment variables. This call was removed a while ago when we ditched the tor_utils module.
