### ISSUE TITLE
no module named 'tbselenium'

### ISSUE THREAD

**Issue by tuxy1965** [webfp/tor-browser-selenium#129]
Traceback (most recent call last):
  File "bot.py", line 4, in <module>
    from tbselenium.tbdriver import TorBrowserDriver
ModuleNotFoundError: No module named 'tbselenium'
That is the error I get while trying to run the simplest of codes to try and just open the browser and close it.
I followed all the instructions to install tbselenium and retried installing it several times however I keep running into this problem. It should also be known that I'm using Visual Studio Code on a linux machine and selenium for Chrome and Firefox works perfectly fine if that helps any.

**Comment by gunesacar** [comment]
If the `tbselenium` installation finished without problems, this must be a problem with your Python setup. Maybe it's a python2 vs python3 issue? Or Visual Studio is not configured to discover the Python paths properly?

What happens when you run the following from the command line?
-  `python -c 'import tbselenium'`
-  `python3 -c 'import tbselenium'`

**Comment by tuxy1965** [comment]
root@kali:~# python3 -c 'import tbselenium'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tbselenium'
The exact same issue.  Should I reconfigure python 3 then?

**Comment by gunesacar** [comment]
Looks like you don't have tbselenium installed for Python3.
`pip3 install tbselenium` may solve your problem.
