### ISSUE TITLE
set geckodriver binary location programmatically

### ISSUE THREAD

**Issue by fontune** [webfp/tor-browser-selenium#137]
Hi guys, I really appreciate this project and it's been a great help.

This may just be me missing something but in [Selenium WebDriver's Documentation](https://www.selenium.dev/documentation/en/webdriver/driver_requirements/#firefox) there is an option to set the geckodriver binary location without using the PATH environment variable. 

In webdriver it's done like this
```python
Firefox(executable_path='/path/to/geckodriver')
```

Is this functionality present in tor-browser-selenium, or is using PATH a requirement? (And if this is not currently an option, do you plan to add it in the future?)

Thank you!

**Comment by gunesacar** [comment]
Thanks @fontune ,
This parameter is not implemented in tor-browser-selenium, but it can easily be added since we subclass FirefoxDriver.

We need to add a new parameter here:
https://github.com/webfp/tor-browser-selenium/blob/master/tbselenium/tbdriver.py#L43
and pass the same parameter to the parent's constructor here:
https://github.com/webfp/tor-browser-selenium/blob/master/tbselenium/tbdriver.py#L65

Are you interested in submitting a PR? It may take a couple of weeks for me to get to this.

**Comment by gunesacar** [comment]
Thanks, @fontune, the PR looks great. 
I'll merge it as soon as the CI tests pass.

**Comment by fontune** [comment]
Sounds good, thanks again for this project and for getting back to me so quickly.
