### ISSUE TITLE
disable images loading

### ISSUE THREAD

**Issue by vorticalbox** [webfp/tor-browser-selenium#184]
I am trying to disable images loading but i cannot seem to get it to work

```python
        firefox_profile = driver.firefox_profile
        firefox_profile.set_preference('permissions.default.image', 2)
        firefox_profile.set_preference('dom.ipc.plugins.enabled.libflashplayer.so', 'false')
```

however this doesn't seem to work

**Comment by gunesacar** [comment]
You may want to pass the preference during initialization, since changes in profile preferences may not immediately be taken into account. See the new test code for an example:

https://github.com/webfp/tor-browser-selenium/blob/698c4a34c6fe0e9d17b87a1a556b89159b7b6ccb/tbselenium/test/test_disable_javascript.py#L17-L30
