### ISSUE TITLE
Trouble with tor binary

### ISSUE THREAD

**Issue by AndrewGalak6578** [webfp/tor-browser-selenium#198]
Hello, I tried to use tbselenium but faced issue with some parameters like tbb_path
Here's how my path to firefox file looks like (/Applications/Tor Browser.app/Contents/MacOS/firefox (not binary, executable file)
And also I don't know where to find my profile path.

And because of that I get error:  Traceback (most recent call last):
  File "/Users/admin/Documents/parser/test.py", line 67, in <module>
    main()
  File "/Users/admin/Documents/parser/test.py", line 38, in main
    with TorBrowserDriver(tbb_path=tor_path, tbb_profile_path=profile_path) as driver:#
  File "/Users/admin/Documents/parser/myenv/lib/python3.9/site-packages/tbselenium/tbdriver.py", line 55, in __init__
    self.setup_tbb_paths(tbb_path, tbb_fx_binary_path,
  File "/Users/admin/Documents/parser/myenv/lib/python3.9/site-packages/tbselenium/tbdriver.py", line 178, in setup_tbb_paths
    raise TBDriverPathError("Invalid Firefox binary %s"
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary /Applications/Tor Browser.app/Contents/Browser/firefox

**Comment by gunesacar** [comment]
Thanks for reporting. You don't have to provide a binary unless you need to use modified browser.
Can you tell more about the use case or share minimal code to reproduce?

**Comment by AndrewGalak6578** [comment]
Well, if I don't provide then I get error (tbselenium.exceptions.TBDriverPathError: Either TBB path or Firefox profile and binary path should be provid). 

Here's a little part from code

import requests
import time
import tbselenium
from tbselenium.tbdriver import TorBrowserDriver
from selenium.webdriver.common.by import By
with TorBrowserDriver() as driver:#
        print("Opening the webpage...")
        driver.get("onion website")

**Comment by AndrewGalak6578** [comment]
How can I just open browser, if it always asks me to give it the path, but when i give it says that this is not correct path

**Comment by gunesacar** [comment]
You should download Tor browser yourself, extract it and pass the path of the extracted folder (not the binary) in the `tbb_path` variable. https://github.com/webfp/tor-browser-selenium#-usage

**Comment by AndrewGalak6578** [comment]
> You should download Tor browser yourself, extract it and pass the path of the extracted folder (not the binary) in the `tbb_path` variable. https://github.com/webfp/tor-browser-selenium#-usage

I did it, but as I said, it gives me error "tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary /Applications/Tor Browser.app/Browser/firefox" with code - tbb_path="/Applications/Tor Browser.app"
with TorBrowserDriver(tbb_path=tbb_path) as driver:

**Comment by gunesacar** [comment]
Unfortunately MacOS is not currently supported.

**Comment by AndrewGalak6578** [comment]
> Unfortunately MacOS is not currently supported.

It's alright, but what system is supported?

**Comment by gunesacar** [comment]
https://github.com/webfp/tor-browser-selenium#%EF%B8%8F-compatibility

**Comment by toolonely** [comment]
> You should download Tor browser yourself, extract it and pass the path of the extracted folder (not the binary) in the `tbb_path` variable. https://github.com/webfp/tor-browser-selenium#-usage

I think this shall be explicitly mentioned in the README. After all, the "getting started" workflow of a new user consists in trying the example listed in the README. By copypasting it. And it won't work. Because `"/path/to/tor-browser/"` is a generic name, because locations are OS specific. Even better to improve ` the path of the extracted folder (not the binary)` by replacing it with `the path of the extracted folder (not the binary), as in the path that contains the Browser/ directory and the start-tor-browser.desktop file`. On my Linux, Tor Browser is started by a distro specific `tor-browser` shell script, which populates `~/.tor-browser/INSTALL` with content similar to what's in the official binary Tor Browser tarball (which I had to download and extract to find that out, as you suggested, so this is an additional, sometimes unnecessary step, if the example in the README can be made a little bit more explicit, as suggested).

It is also worth mentioning in the said example in the README that absolute paths have to be used. So "/home/user/.tor-browser/INSTALL/" (see above) will work, while "~/.tor-browser/INSTALL/" will fail with

    tbselenium.exceptions.TBDriverPathError: TBB path is not a directory ~/.tor-browser/INSTALL/

**Comment by gunesacar** [comment]
Good suggestions, @toolonely . I'm reopening this issue to track it.

> `tbselenium.exceptions.TBDriverPathError: TBB path is not a directory ~/.tor-browser/INSTALL/`

We can also use `os.path.expandpath`  to convert relative paths to absolute.

**Comment by gunesacar** [comment]
Added a clarification to https://github.com/webfp/tor-browser-selenium#-usage.

**Comment by gunesacar** [comment]
PRs to improve the installation instructions in the README are welcome.

**Comment by toolonely** [comment]
README is much better now, just needs `s/not pass pass/not pass/`.

**Comment by gunesacar** [comment]
> README is much better now, just needs `s/not pass pass/not pass/`.

Thanks for the heads up. Fixed: https://github.com/webfp/tor-browser-selenium/commit/2f5cbba299d961ce19b7ac001a5a5a5c1af5499c
