### ISSUE TITLE
Improve the interface to take screenshots

### ISSUE THREAD

**Issue by mjuarezm** [webfp/tor-browser-selenium#2]
Currently, if a user wants to take screenshots of the pages visited with the driver, he will need to add all the URLs as _exceptions_ using the class method `TorBrowserDriver.add_exception()` **before instantiating the TorBrowserDriver**.

Adding an exception means granting permissions to a domain to access the Canvas, otherwise restricted by the TorBrowser to protect against browser fingerprinting. Selenium requires access to the Canvas to take the screenshot. However, the changes we commit to `permissions.sqlite` do not have any effect when the browser is running (probably the database is loaded into memory by Firefox).

The aim of this ticket is to improve the interface for taking screenshots so that users do not need to add an exception for each future visit beforehand. We need to investigate if there is a way to refresh the permissions loaded in the browser on runtime.

**Comment by gunesacar** [comment]
Now we [accept the allowed canvas URLs as an array](https://github.com/webfp/tor-browser-selenium/blob/2c26bc5b66e7cfb90da5f358e5c8c4e635fa1e7c/tbselenium/tbdriver.py#L36) during the initialization. More importantly, **TBB >= 4.5a3 doesn't require canvas permission to take screenshot** since the chrome scripts are exempted from the canvas permission.

See, https://trac.torproject.org/projects/tor/ticket/13439
